name: Fast Tests

on:
  pull_request:
    branches:
      - master

jobs:
  suit: 
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run tests...
        run: time make tests TESTS_FLAGS="-f"
