name: Full Tests

on:
  push:
    branches:
      - master

jobs:
  suit: 
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run tests...
        run: time make tests-coverage
